version: '2'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/source
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
