# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import photos.fields
import photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', validators=[photos.validators.validate_photo_extension])),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbs')),
                ('concepts', photos.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
