# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import photos.fields
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='concepts',
            field=photos.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[photos.validators.validate_photo_extension]),
        ),
    ]
